import { Metadata } from 'next'
import{Inter} from "next/font/google";
import"./globals.css";
import NavBar from "./components/employeecomponents/navbar";
import Link from 'next/link';

const inter=Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description:"Generated by create next app",
}
export default function RootLayout({
  children,
}:Readonly< {
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <h1>Header</h1>   */}
      {/* <NavBar/><br></br>
      <Link href="./signin">SignIn</Link> <br></br>
      <Link href="./signup">SignUp</Link> <br></br> */}
        {children}
      {/* <h1>Footer</h1>   */}
      
      </body>
      
    </html>
    
  )
}